// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEB2_Backend.Database.Context;

namespace WEB2_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WEB2_Backend.Model.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Coordinates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EqType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Masarikova 12",
                            Coordinates = "None",
                            EqType = 0,
                            Name = "SW1",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            Address = "Masarikova 12",
                            Coordinates = "None",
                            EqType = 2,
                            Name = "TR1",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            Address = "Cara Dusana 50",
                            Coordinates = "None",
                            EqType = 1,
                            Name = "FU1",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            Address = "Cara Dusana 90",
                            Coordinates = "None",
                            EqType = 3,
                            Name = "DI1",
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("WEB2_Backend.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserT")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Novi Sad",
                            Birthday = new DateTime(1997, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "godlike.jovan@gmail.com",
                            Image = "",
                            IsDeleted = false,
                            LastName = "Miljkovic",
                            Name = "Jovan",
                            Password = "jovan123",
                            UserT = 3,
                            Username = "AdminJovan",
                            isActive = true
                        },
                        new
                        {
                            Id = 2,
                            Address = "Novi Sad",
                            Birthday = new DateTime(1997, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "srdjandzinovic97@gmail.com",
                            Image = "",
                            IsDeleted = false,
                            LastName = "Dzinovic",
                            Name = "Srdjan",
                            Password = "dzin123",
                            UserT = 1,
                            Username = "DispatcherDzin",
                            isActive = true
                        },
                        new
                        {
                            Id = 3,
                            Address = "Novi Sad",
                            Birthday = new DateTime(1997, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "joci.miljkovic@gmail.com",
                            Image = "",
                            IsDeleted = false,
                            LastName = "Miljkovic",
                            Name = "Jovan",
                            Password = "jovan123",
                            UserT = 2,
                            Username = "WorkerJovan",
                            isActive = true
                        },
                        new
                        {
                            Id = 4,
                            Address = "Novi Sad",
                            Birthday = new DateTime(1994, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dejanbozic@gmail.com",
                            Image = "",
                            IsDeleted = false,
                            LastName = "Bozic",
                            Name = "Dejan",
                            Password = "dejan123",
                            UserT = 0,
                            Username = "CrewDejan",
                            isActive = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
